import Head from 'next/head'
export default function pageLayout ({children, title='NewsApp'}) {
    return (
        <>
            <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    <header>
        🗞 news api
        </header>
        <main>
            {children}
        </main>
    <style jsx>{`
        header {
        padding: 20px;
        }
    `}</style>
  </>
    )
}